### ISSUE TITLE
the docs should include an example of sdk-initiation with custom kin-issuers

### ISSUE THREAD

**Issue by fuzzyami** [kinecosystem/kin-core-python#30]
`from stellar_base.asset import Asset
kin_asset = Asset('KIN', config.STELLAR_KIN_ISSUER_ADDRESS)

app.kin_sdk = kin.SDK(secret_key=base_seed,
                      horizon_endpoint_uri=config.STELLAR_HORIZON_URL,
                      network=config.STELLAR_NETWORK,
                      channel_secret_keys=channel_seeds,
                      kin_asset=kin_asset)`

**Comment by Ronserruya** [comment]
This is being done in kin-core-v2
